### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [AndyCao1125/SDDPM#1]
Dear Authors,

How long does your method need to train?

**Comment by Guohanzhong** [comment]
Training costs about 32 ~A100 days on CIFAR-10.

**Comment by QgZhan** [comment]
> Training costs about 32 ~A100 days on CIFAR-10.

Does this mean that it takes 32 days to train CIFAR10 on one A100?

**Comment by AndyCao1125** [comment]
Correct.
