### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by weiruchess** [AndyCao1125/SDDPM#2]
Hello author,

Thank you for your code. However, I encountered the following error when running the program with the command "CUDA_VISIBLE_DEVICES=0 python main_SDDPM.py --train":

```
RuntimeError: The size of tensor a (64) must match the size of tensor b (32) at non-singleton dimension 0.
```

But when I set "total_steps" to 1, the error disappears. I hope to get your explanation or solution for this issue.

Thank you!

**Comment by AndyCao1125** [comment]
Thanks for your question. If you hope to use one GPU to train the SDDPM, one solution to prevent this error is to make sure that _args.batch_size_ is equal to _args.sample_size_, and set _args.parallel = False_. But we strongly recommand to use muli-GPUs, e.g., _CUDA_VISIBLE_DEVICES=0,1 python main_SDDPM.py --train --parallel=True_.
