### ISSUE TITLE
question for weight

### ISSUE THREAD

**Issue by chaibosong** [AndyCao1125/SDDPM#6]
Another small question, the cifa weight file you provided is about 1.9G, and the weight I trained myself is 763M. What is the reason for this?

**Comment by AndyCao1125** [comment]
Thanks for your question. 
Because this file also holds the ema version of SNN-UNet (the same size as 'net_model') as well as other training objects such as optim, hence this ckpt file is large. You can check the items contained in ckpt by print("Keys in checkpoint:", list(ckpt.keys())).
