### ISSUE TITLE
MembraneOutputLayer

### ISSUE THREAD

**Issue by tonia86** [AndyCao1125/SDDPM#8]
非常感谢您能开源这个代码。有一个问题，想请教您。在 MembraneOutputLayer 类中，权重“0.8”的设置引起了我的注意。请问这个权重是基于什么原则或实验结果确定的？是否有相关的文献或实验支持这一选择？

**Comment by AndyCao1125** [comment]
Thank you for your question. @tonia86 
The MembraneOutputLayer we employed comes from FSVAE ([paper](https://arxiv.org/pdf/2110.00375) & [code](https://github.com/kamata1729/FullySpikingVAE/blob/ffadb3d4bf4fe02927acb241ac11e6ad693c22dc/fsvae_models/snn_layers.py#L291)). This layer utilizes the final membrane potential as output, which not only preserves essential features but also serves as a necessary process for spike-to-image conversion (e.g., binary-to-float). We believe this approach is justified, so we adopted it directly without introducing new designs in this context. Future explorations may contribute to performance enhancement.
